In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.csv")
dt = pd.read_csv("test.csv")

In [3]:
# null values for test and train sets.
print(df.isnull().sum())
print(dt.isnull().sum())

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64
ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64


In [4]:
# unique values for test and train sets.
print(df.nunique())
print(dt.nunique())

ID      4209
y       2545
X0        47
X1        27
X2        44
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 378, dtype: int64
ID      4209
X0        49
X1        27
X2        45
X3         7
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 377, dtype: int64


In [5]:
Y_dt = dt.drop(labels=['ID'],axis = 1)

In [6]:
Y_dt.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   
3  az  l   n  f  d  z  l  n    0    0  ...     0     0     0     1     0   
4   w  s  as  c  d  y  i  m    0    0  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 376 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
Y_dt_Y = Y_dt.apply(le.fit_transform)

In [10]:
Y_dt_Y.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 376 columns]

In [11]:
df = df.drop(labels=['ID'],axis = 1)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
X_df = df.apply(le.fit_transform)

In [15]:
X_df.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  2466  32  23  17   0   3  24   9  14    0  ...     0     0     1     0   
1   366  32  21  19   4   3  28  11  14    0  ...     1     0     0     0   
2    69  20  24  34   2   3  27   9  23    0  ...     0     0     0     0   
3   133  20  21  34   5   3  27  11   4    0  ...     0     0     0     0   
4   106  20  23  34   5   3  12   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 377 columns]

In [16]:
from sklearn.feature_selection import VarianceThreshold

In [17]:
vt = VarianceThreshold(threshold=0)

In [18]:
X_df_X = vt.fit_transform(X_df)

In [19]:
X_df_X = vt.get_support()

In [20]:
sum(vt.get_support())

365

In [21]:
constant_columns = [columns for columns in X_df.columns
                     if columns not in X_df.columns[X_df_X]]

In [22]:
constant_columns

['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347']

In [23]:
X_new = X_df.drop(labels = ['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347'],axis =1)

In [24]:
X_new.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  2466  32  23  17   0   3  24   9  14    0  ...     0     0     1     0   
1   366  32  21  19   4   3  28  11  14    0  ...     1     0     0     0   
2    69  20  24  34   2   3  27   9  23    0  ...     0     0     0     0   
3   133  20  21  34   5   3  27  11   4    0  ...     0     0     0     0   
4   106  20  23  34   5   3  12   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 365 columns]

In [25]:
X_new = X_new.drop(labels = ['y'],axis = 1)

In [26]:
X_new.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1  32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2  20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3  20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4  20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [27]:
Y_new = Y_dt_Y.drop(labels = ['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347'],axis =1)

In [28]:
Y_new.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
mm = MinMaxScaler()

In [31]:
mm.fit(Y_new)

MinMaxScaler()

In [32]:
scaler_dt = mm.transform(Y_new)

In [33]:
scaler_dt

array([[0.4375    , 0.88461538, 0.77272727, ..., 0.        , 0.        ,
        0.        ],
       [0.875     , 0.11538462, 0.18181818, ..., 0.        , 0.        ,
        0.        ],
       [0.4375    , 0.88461538, 0.38636364, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.97916667, 0.88461538, 0.38636364, ..., 0.        , 0.        ,
        0.        ],
       [0.14583333, 0.88461538, 0.38636364, ..., 0.        , 0.        ,
        0.        ],
       [0.875     , 0.03846154, 0.18181818, ..., 0.        , 0.        ,
        0.        ]])

In [34]:
dt_scaler = pd.DataFrame(scaler_dt, index=Y_new.index, columns=Y_new.columns)

In [35]:
dt_scaler.head()

X0        X1        X2        X3   X4        X5        X6        X8  \
0  0.4375  0.884615  0.772727  0.833333  1.0  0.838710  0.000000  0.916667   
1  0.8750  0.115385  0.181818  0.000000  1.0  0.290323  0.545455  1.000000   
2  0.4375  0.884615  0.386364  0.833333  1.0  0.000000  0.818182  0.375000   
3  0.4375  0.500000  0.772727  0.833333  1.0  1.000000  1.000000  0.541667   
4  0.9375  0.769231  0.386364  0.333333  1.0  0.967742  0.727273  0.500000   

   X10  X12  ...  X375  X376  X377  X378  X379  X380  X382  X383  X384  X385  
0  0.0  0.0  ...   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
1  0.0  0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2  0.0  0.0  ...   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
3  0.0  0.0  ...   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
4  0.0  0.0  ...   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 364 columns]

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
mm = MinMaxScaler()

In [38]:
mm.fit(X_new)

MinMaxScaler()

In [39]:
scaler_data = mm.transform(X_new)

In [40]:
scaler_data

array([[0.69565217, 0.88461538, 0.39534884, ..., 0.        , 0.        ,
        0.        ],
       [0.69565217, 0.80769231, 0.44186047, ..., 0.        , 0.        ,
        0.        ],
       [0.43478261, 0.92307692, 0.79069767, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.17391304, 0.88461538, 0.88372093, ..., 0.        , 0.        ,
        0.        ],
       [0.19565217, 0.73076923, 0.58139535, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.73076923, 0.06976744, ..., 0.        , 0.        ,
        0.        ]])

In [41]:
df_scaler = pd.DataFrame(scaler_data, index=X_new.index, columns=X_new.columns)

In [42]:
df_scaler.head()

X0        X1        X2        X3   X4        X5        X6        X8  \
0  0.695652  0.884615  0.395349  0.000000  1.0  0.857143  0.818182  0.583333   
1  0.695652  0.807692  0.441860  0.666667  1.0  1.000000  1.000000  0.583333   
2  0.434783  0.923077  0.790698  0.333333  1.0  0.964286  0.818182  0.958333   
3  0.434783  0.807692  0.790698  0.833333  1.0  0.964286  1.000000  0.166667   
4  0.434783  0.884615  0.790698  0.833333  1.0  0.428571  0.272727  0.541667   

   X10  X12  ...  X375  X376  X377  X378  X379  X380  X382  X383  X384  X385  
0  0.0  0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1  0.0  0.0  ...   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
3  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 364 columns]

In [43]:
from sklearn.decomposition import PCA

In [44]:
pca = PCA(n_components= 10)

In [45]:
pca.fit(dt_scaler)

PCA(n_components=10)

In [46]:
pca_dt = pca.transform(df_scaler)

In [47]:
pca_dt

array([[ 0.62923161,  1.9287776 , -1.7506126 , ..., -0.91654255,
         0.07499722, -0.55846988],
       [-0.18488571, -0.31909474, -1.30300841, ..., -0.4258338 ,
        -0.19800144,  0.47070098],
       [-0.91206204,  1.51104974, -2.74763977, ...,  0.45309386,
        -1.12360227, -0.42978013],
       ...,
       [-1.1909663 ,  1.78284081, -0.31057826, ..., -1.94224648,
         1.87507838,  0.46829759],
       [ 0.50055066, -2.92131038, -0.67252281, ..., -0.76019487,
        -0.41234597,  0.58883887],
       [ 0.88946773, -1.04640403, -0.57826114, ...,  1.97835168,
        -0.07697104, -0.06607827]])

In [48]:
from sklearn.decomposition import PCA

In [49]:
pca = PCA(n_components= 10)

In [50]:
pca.fit(df_scaler)

PCA(n_components=10)

In [51]:
pca_data = pca.transform(df_scaler)

In [52]:
x = pca_data

In [53]:
Y = X_df['y']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,Y_train,Y_test = train_test_split(x,Y,test_size = 0.3,random_state=20)

In [56]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_squared_error

In [57]:
xgb = XGBRegressor(subsample= 1,max_depth=5,learning_rate=0.05,gamma=1,reg_alpha=10,n_estimators=150,colsample_bylevel=1)

In [58]:
xgb.fit(x_train, Y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=1, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.05, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=5, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=150, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0,
             reg_alpha=10, reg_lambda=1, ...)

In [59]:
pred_xgb = xgb.predict(x_test)

In [60]:
print(r2_score(Y_test,pred_xgb))

0.5683786332050966


In [61]:
pred_xgb = xgb.predict(pca_dt)

In [62]:
pred_xgb

array([1238.7025 ,  944.8275 ,  222.40718, ..., 1621.1953 , 1049.1226 ,
       1233.636  ], dtype=float32)